export const SPECIALTY_OPTIONS = [
  "Internal Medicine",
  "Pediatrics & Maternal-Child Health",
  "Gynecology & Obstetrics",
  "General Surgery",
  "Cardiology",
  "Orthopedics",
  "ENT (Ear, Nose, Throat)",
  "Dermatology",
  "Psychiatry & Mental Health",
  "Ophthalmology (Eye Care)",
  "Physiotherapy",
  "Dental",
  "Neurology",
  "Oncology",
  "Gastroenterology",
  "Multiple specialties",
  "Other",
] as const;

export const SUB_CITIES = [
  "Addis Ketema",
  "Akaki Kaliti",
  "Arada",
  "Bole",
  "Gulele",
  "Kirkos",
  "Kolfe Keranio",
  "Lemi Kura",
  "Lideta",
  "Nifas Silk-Lafto",
  "Sheger City",
  "Yeka",
] as const;
